name: Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'  # version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: df -h /
    - run: |
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/hostedtoolcache
        sudo rm -rf /opt/google/chrome
        sudo rm -rf /opt/microsoft/msedge
        sudo rm -rf /opt/microsoft/powershell
        sudo rm -rf /opt/pipx
        sudo rm -rf /usr/lib/mono
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/lib/node_modules
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
    - run: df -h /
    - run: sleep 10
    - run: df -h /

    - run: ./docker/build.sh
  
    - run: ./docker/push.sh ${{ secrets.DOCKERHUB_USERNAME }}/llgtrt
      if: startsWith(github.ref, 'refs/tags/v')
