name: Docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'  # version tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v4
      with:
        submodules: true

    - run: ./docker/gh-cleanup.sh

    - run: ./docker/build.sh llgtrt_dev
  
    - run: ./docker/build.sh llgtrt_prod
  
    - run: ./docker/push.sh ${{ vars.DOCKERHUB_USERNAME }}/llgtrt
      if: startsWith(github.ref, 'refs/tags/v')
